name: chatgpt_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.9
  shared_preferences: ^2.0.17
  flutter_svg: ^1.1.6
  get: ^4.6.5
  lottie: ^2.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/paradise_beach.jpg
    - images/booking.jpg
    - images/restaurant.jpg
    - images/airport_panel.jpg
    - images/review.jpg
    - images/city.jpg
    - images/mountain.jpg
    - images/chat_logo.png
    - images/openai_logo.jpg
    - images/person.png
    - assets/loading.json
    - assets/loadingBar.json

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
